name: handwriting
sessions:
  - 2022.05.18
  - 2022.05.23
  - 2022.05.25
  - 2022.06.01
  - 2022.06.03
  - 2022.06.06
  - 2022.06.08
  - 2022.06.13
  - 2022.06.15
  - 2022.06.22
  - 2022.09.01
  - 2022.09.29
  - 2022.10.06
  - 2022.10.18
  - 2022.10.25
  - 2022.10.27
  - 2022.11.01
  - 2022.11.03
  - 2022.12.08
  - 2022.12.15
  - 2023.02.28
  - 2023.04.17
  - 2023.05.31
  - 2023.06.28
datasetToLayerMap:
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
datasetProbability:
datasetProbabilityVal:
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
dataDir:
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_in_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_out_oracle_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_out_oracle_tfrecords/
 - /oak/stanford/groups/henderj/stfan/code/CORP/FalconChallenge/data/held_out_oracle_tfrecords/
syntheticDataDir:
syntheticMixingRate: 0.0
whiteNoiseSD: 1.2
constantOffsetSD: 0.6
randomWalkSD: 0.02
nInputFeatures: 192
timeWarpFactor: 0.0
staticGainSD: 0.0
nClasses: 31
maxSeqElements: 500

# Dataset shuffle buffer size
bufferSize: 192
