name: handwriting
sessions:
  - t5.2019.05.08
  - t5.2019.11.25
  - t5.2019.12.09
  - t5.2019.12.11
  - t5.2019.12.18
  - t5.2019.12.20
  - t5.2020.01.06
  - t5.2020.01.08
  - t5.2020.01.13
  - t5.2020.01.15
datasetToLayerMap: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
datasetProbability:
datasetProbabilityVal: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,]
dataDir:
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/henderj/stfan/data/handwriting_data/normalize_with_block_means
syntheticDataDir:
syntheticMixingRate: 0.0
whiteNoiseSD: 1.2
constantOffsetSD: 0.6
randomWalkSD: 0.02
nInputFeatures: 192
timeWarpFactor: 0.0
staticGainSD: 0.0
nClasses: 31
maxSeqElements: 500

# Dataset shuffle buffer size
bufferSize: 192
