defaults:
  - submitit_slurm

timeout_min: 2880  # 2 days
cpus_per_task: 4
mem_gb: 32
partition: henderj,owners
gpus_per_node: 1
setup:
  - ml load cudnn/8.6.0.163
additional_parameters:
  constraint: '[GPU_MEM:24GB|GPU_MEM:32GB|GPU_MEM:40GB|GPU_MEM:80GB]'
  mail-type: ALL
array_parallelism: 50
